apiVersion: v1
kind: Service
metadata:
  name: n9e-mysql
  namespace: n9e
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: n9e-mysql
  sessionAffinity: None
  type: NodePort
